App\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        UNIQ_8D93D649F85E0677:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        roles:
            type: text
            nullable: false
            length: 0
            options:
                fixed: false
        apiToken:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: api_token
    lifecycleCallbacks: {  }
